# -*- coding: utf-8 -*-
"""parte_pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WEnx6FVe6jSw1XxU9C0kR7UWpX17KOJn
"""

import pandas as pd
df=pd.read_csv('Dataset_Processo_Seletivo_UFRJ_Analytica_2022.1.csv')
print(df)

def IDH_1991(df):
  'Calcula a média do IDH em 1991'
  filtro1= df[df['ano']==1991]
  filtro2=df['idhm']
  df_filtrado=df[ (df['ano'] == 1991) & (df['idhm']) ]
  soma=0
  for idh in df_filtrado.iloc[:,5]:
      soma+=idh
  return soma/len(filtro1)

media=IDH_1991(df)
print(media)

filtro1=df[df['ano']==1991]

def UF_maior(df,media:float):
  'imprime os estados que estão acima da média, também no ano de 1991'
  filtro1=df[df['ano']==1991]
  filtro2=df[df['idhm']>media]
  df_filtrado=df[ (df["ano"] == 1991) & (df["idhm"] > media) ]
  print(df_filtrado)

print(UF_maior(df,media))

def ordena_idh(filtro1):
  'Ordena os dados do DataFrame de 1991, a partir do IDH'
  em_ordem=filtro1.sort_values(by='idhm')
  print(em_ordem.head(5))

print(ordena_idh(filtro1))

def analise_idh(df):
  'Mostra os estado com maior e menor idh'
  filtro1=df[df['ano']==1991]
  filtro2=df['idhm']
  df_filtrado=df[ (df["ano"] == 1991) & (df["idhm"]) ]
  maior=df_filtrado['idhm'].max()
  menor=df_filtrado['idhm'].min()
  indice_M=df_filtrado['idhm'].idxmax()
  indice_m=df_filtrado['idhm'].idxmin()
  print(df.iloc[indice_M]) #maior IDH
  print(df.iloc[indice_m]) #menor IDH


print(analise_idh(df))